# Generated by Django 5.0.3 on 2024-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_rename_is_active_usuario_usuarioactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dv',
            field=models.CharField(max_length=1, verbose_name='Dígito Verificador'),
        ),
    ]
