# Generated by Django 5.0.3 on 2024-06-04 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_personas', models.IntegerField(verbose_name='Cantidad de personas')),
                ('fecha', models.DateField(verbose_name='Fecha de reserva')),
                ('terminosCondiciones', models.BooleanField(default=False, verbose_name='Términos y Condiciones')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
