# Generated by Django 5.0.3 on 2024-06-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad de días'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto',
            field=models.IntegerField(default=0, verbose_name='Monto'),
        ),
    ]
