# Generated by Django 5.0.6 on 2024-06-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_vencimiento',
        ),
    ]
