# Generated by Django 5.0.6 on 2024-06-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_cantidad_dias_reserva_monto'),
        ('reservas', '0005_reserva_monto'),
    ]

    operations = [
    ]
