# Generated by Django 5.0.6 on 2024-06-10 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad de días'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento de reserva'),
        ),
    ]
