# Generated by Django 5.0.6 on 2024-06-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_merge_20240613_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
