# Generated by Django 5.0.3 on 2024-05-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT')),
                ('primerNombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('segundoNombre', models.CharField(blank=True, max_length=50, verbose_name='Segundo Nombre')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo Apellido')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo')),
                ('terminosCondiciones', models.BooleanField(default=False, verbose_name='Términos y Condiciones')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuarioAdministrador', models.BooleanField(default=False, verbose_name='Administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
