# Generated by Django 5.0.3 on 2024-05-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_usuario_dv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primerApellido',
            field=models.CharField(max_length=20, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primerNombre',
            field=models.CharField(max_length=20, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(max_length=8, primary_key=True, serialize=False, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundoApellido',
            field=models.CharField(blank=True, max_length=20, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundoNombre',
            field=models.CharField(blank=True, max_length=20, verbose_name='Segundo Nombre'),
        ),
    ]
