# Generated by Django 5.0.3 on 2024-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_usuario_correo_alter_usuario_primerapellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT'),
        ),
    ]
